### ISSUE TITLE
Create a system for telemedicine / online consultation management

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#10]
Use case: If we move a lockdown, It would be hard to connect with doctors/get consultation. 

Features required: 
- [ ] A page to where people could visit and enter details
- [ ] Capture basic patient information and problems they are facing. 
- [ ] Give 3 options to choose [Genral consultation, Emergency consultation, Counsiling]
- [ ] - setup a consulation. Phone / Video Call (check posibilities)

# Exotel has agreed to helpout with API

**Comment by jithinlal** [comment]
So only the frontend? If so what framework? I could help with this.

**Comment by saanuregh** [comment]
could use this for video conferencing 
https://github.com/jitsi/jitsi-meet
its scalable and no pricing constriction unlike zoom

as far as i know exotel dont provide any video conferencing service

**Comment by saanuregh** [comment]
is anyone working one this?

**Comment by bodhish** [comment]
http://telemedicine.coronasafe.network/

**Comment by nksoft-corp** [comment]
Did you create a solution?

**Comment by bodhish** [comment]
Yep @nksoft-corp

**Comment by alexsam986** [comment]
For your online consultation and telemedicine, you must have features like in-app chat, voice, and video chats, and maybe live streaming for occasional information sessions. 

Building all these functionalities, starting from scratch, requires an excellent chat infrastructure, resources, and time. I'd suggest using Chat APIs and SDKs to hit a quick launch by accompanying all the necessary ones. 

Here is a detailed guide to choosing the best video calling APIs in the industry for your online consultation/telemedicine. [https://www.trustfirms.com/live-video-calling-apis-sdks-for-web-mobile-apps](https://www.trustfirms.com/live-video-calling-apis-sdks-for-web-mobile-apps)
