### ISSUE TITLE
Create a data visualization map for kerala. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#11]
The data source should be identified. You can refer the data set give in [beginnersguide.coronasafe.network](beginnersguide.coronasafe.network) 

![Screenshot_20200322-101843](https://user-images.githubusercontent.com/14979190/77242699-2c3de680-6c27-11ea-9bd6-58cc55949e39.jpg)

**Comment by Ascalonic** [comment]
We dont have consistent cases in kerala to begin with as of now. US has now got hundreds of cases in each state.

**Comment by saanuregh** [comment]
im working on a interactive map visualization for kerala inspired by https://www.covid19india.org/

**Comment by saanuregh** [comment]
Here is my attempt at it, 
https://saanuregh.github.io/covid19-kerala/
mobile responisive as well
the data might be wrong since the endpoint https://volunteer.coronasafe.network/api/reports is broken

**Comment by bodhish** [comment]
@saanuregh messgae me on slack

**Comment by bodhish** [comment]
@saanuregh you can a create a repo on the org so that others could also contibute

**Comment by dauntlessnomad** [comment]
issue coml
