### ISSUE TITLE
Parse dhs daily bulletin to feed the stats api

### ISSUE THREAD

**Issue by dauntlessnomad** [coronasafe/Features#17]
http://dhs.kerala.gov.in/2020/ URL endpoint
@solancer

**Comment by ramuz108** [comment]
we need to have a database as well right?

**Comment by bodhish** [comment]
Data | URL
-- | --
Time-series District-wise Histories of COVID-19 stats | https://keralastats.coronasafe.live/histories.json
Latest District-wise COVID-19 stats | https://keralastats.coronasafe.live/latest.json
Latest Summary of COVID-19 stats | https://keralastats.coronasafe.live/summary.json
Time-series Test Reports | https://keralastats.coronasafe.live/testreports.json
Time-series Hotspots Histories | https://keralastats.coronasafe.live/hotspots_histories.json
Latest Hotspots | https://keralastats.coronasafe.live/hotspots.json
Time-series District-wise Zones Histories | https://keralastats.coronasafe.live/zones_histories.json
Latest District-wise Zones | https://keralastats.coronasafe.live/zones.json
