### ISSUE TITLE
System to manage corona care center (CCC)

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#3]
A Corona Care Center is a temporary facility created to augment the healthcare system of the state and country in anticipation to a wide-spread pandemic. 

This is created by converting Educational Institutions like Schools and Colleges into centers where patients in the locality can reach out for help.

Detailed requirment: http://model.coronasafe.in/
Dev documentation: http://dev.coronasafe.in/

**Comment by bodhish** [comment]
In progress, [github.com/coronasafe/care](https://github.com/coronasafe/care)

**Comment by codename062** [comment]
Reference
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/technical-guidance/surveillance-and-case-definitions
https://docs.google.com/document/d/12-pex7VOMoRAnsiIcTLq0mTD6UTSfVBZWIX0vufIt6I/edit

**Comment by bodhish** [comment]
Handled by http://care.coronasafe.network/
