### ISSUE TITLE
Store and Analyse the daily status report for India

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#4]
Data could sourced from: https://www.mohfw.gov.in/

- [ ] The daily numbers should be stored and displayed
- [ ] The diff of numbers on each day should be shown state wise. 
- [ ] A Job should check the corectness of the value every 10 mins
- [ ] Figure out the update requency of mohfw

**Comment by aswinmohanme** [comment]
Maybe build a single dashboard that contains all the information ?

**Comment by aswinmohanme** [comment]
#2 and #1 can be merged with this maybe ?

**Comment by bodhish** [comment]
Yes that works. I started a repo to store this values. We can club these after the first round. 
@aswinmohanme 
I was nothing down the ideas. Add your ideas. Let's share this with people intrested to work.

**Comment by bodhish** [comment]
https://covidout.in/ is a good example

**Comment by codename062** [comment]
Someone has already created this and is maintaining it.
https://github.com/gulan28/covid19-viz

**Comment by scarface-49** [comment]
As a next level,  each state should be able to get data district wise.
The Key info as a trend chart will be death rate vs recovered cases

**Comment by bodhish** [comment]
We have a similar plot at map.coronasafe.in where the kerala data is supplied.

We should ideally create something like this. 

https://co.vid19.sg/

**Comment by iamunni** [comment]
What us the status of this prpject? Has someone started working on this? Then I can also join and work together.

**Comment by akaushal123** [comment]
What are the remaining checkpoints? I want to contribute.

**Comment by codename062** [comment]
District vise data
https://www.covid19india.org/

**Comment by bodhish** [comment]
handled in https://map.coronasafe.network/
