### ISSUE TITLE
Create heat map to plot Nation wide data 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#5]
Currently done by map.coronasafe.in

**Comment by bodhish** [comment]
We have district wise data for kerala and state stats for India.

github.com/coronasafe/india-maps

**Comment by NishaKurur** [comment]
https://coronavirus.jhu.edu/map.html is the similar approach from John Hopkins University. This shows different values than that of what is shown in map.coronasafe.in. From where do we fetch data?

**Comment by bodhish** [comment]
https://map.coronasafe.network/
