### ISSUE TITLE
Corona Literacy Mission 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#6]
Translate a curated list of articles from `who`

Complete 
- English - coronasafe.in 
- malayalam - ml.coronasafe.in

In progress
- Hindi 
- Kannada 
- Tamil 
- Telugu

**Comment by Kiransukumaran** [comment]
If you could create a repo for Hindi, I can start translating the contents

**Comment by bodhish** [comment]
transilated to 7 local languages
