### ISSUE TITLE
Create a COVID-19 infection live reporting system

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#7]
Create a COVID-19 infection live reporting system. 
- [ ] Its should have a dashboard to see the data.
- [ ]  It should have use option to add the data 
- [ ] The tables should hold the data district wise.
- [ ] At a later stage, Facilites should also be able to enter the data. 

Sample data 
![WhatsApp Image 2020-03-15 at 10 50 19 PM](https://user-images.githubusercontent.com/14979190/76707288-ddb6b680-6713-11ea-908a-b5baf74fb307.jpeg)

# Secondary Checklist
- [ ] Add columns to enter avilable beds count

**Comment by bodhish** [comment]
A Wip version is now live at volunteer.coronasafe.network


Repo github.com/coronasafe/stats

**Comment by codename062** [comment]
For reference.
https://github.com/gulan28/covid19-viz

**Comment by bodhish** [comment]
We are just capturing the basic data with stats app to feed the map.coronasafe.network

This can be an App of its own.

**Comment by ferbin17** [comment]
is this application in progres ? 
i can help to bring these feature if it has to brought up in the stats app with rails

**Comment by ferbin17** [comment]
i can do this.
actually i have started working on this.!
dashboard, data addition, live report table is completed
there are some more functional parts and many ui fixes need to completed
![add data](https://user-images.githubusercontent.com/20367826/77292298-0a676100-6d06-11ea-8bcc-7bab5e705fdb.png)
![Dashboard](https://user-images.githubusercontent.com/20367826/77292320-12270580-6d06-11ea-830d-2e1df77d0a5f.png)
![Report Page](https://user-images.githubusercontent.com/20367826/77292328-16ebb980-6d06-11ea-9577-ac56fe724e38.png)

**Comment by codename062** [comment]
Any way if you can make the output format to match with that of the JHU or the mohfw.gov.in dataset format in addition to the existing data would be very helpful.
Country,State,District,Latitude,Longitude,Last Update Date/Time,Confirmed,Deaths,Recovered

**Comment by codename062** [comment]
It would be helpful if you you could make the data available in time_series format.
Reference: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

**Comment by ferbin17** [comment]
Apart Latitude and Longitude, rest of the fields are already added in that app
i will add those two also

**Comment by codename062** [comment]
Reference:
Case status reporting system.
https://www.mohfw.gov.in/pdf/NotificationofICMguidelinesforCOVID19testinginprivatelaboratoriesiIndia.pdf

**Comment by ferbin17** [comment]
https://covid-live-report-apps.herokuapp.com
This is a model of  what i am working on.

This is far from complete.
I will tried to finish a working app with minimal features by today
Additional features will be added after that

Credentials:
admin@example.com
password

**Comment by gauravkrthakur1** [comment]
Few References for API's 
[https://covid-19-apis.postman.com/?mkt_tok=eyJpIjoiWmpWak5UY3lOR1EzTVRWbCIsInQiOiIyd3J5WkNjNUhmeElycllCRTAweWZ3RXo0MFB3RGtEdlZBSHdvTVNlVWxxNTJVdGJOc1JsZ2QrZFh4d1wvaEM5V2c5Sis2NDBvZDdwdTFcL1FyS1dYdXR2d1pSWElJYXNzTFJZcXZ4NXJpQ3oyeHlSckF1b2xYOFJ6MGc1YjFCZUFQIn0%3D](url)

**Comment by bodhish** [comment]
Handled by https://care.coronasafe.network/
