### ISSUE TITLE
Create system to store creatives at a single location.

### ISSUE THREAD

**Issue by bodhish** [coronasafe/Features#8]
- [x] Backend - Currently live  - check with @tomahawk-pilot 
- [ ] Frontend - pending

**Comment by dauntlessnomad** [comment]
Backend Api done

**Comment by dauntlessnomad** [comment]
auth jwt access policies and APi tokens

**Comment by jagannathBhat** [comment]
which repo does this issue concern?

**Comment by dauntlessnomad** [comment]
front end no repos as of now

**Comment by dauntlessnomad** [comment]
will create a react skeleton with hooks. by eveing and will define the api
 structure

**Comment by jagannathBhat** [comment]
I do know React. I can help.

**Comment by sanoopbhaskerv** [comment]
I am a front end developer, I can help with front end works.

**Comment by bodhish** [comment]
Need volunteers to curate content
https://github.com/coronasafe/infographics-frontend
